### PR TITLE
Copied over test_sooty_particles from holopy and implemented core-shells into calc_g and calc_efficiencies

### PR DESCRIPTION
**Pull request by victoriahwang89**

### CODE REVIEW

**Comment by vnmanoharan** [comment]
I'm not sure if you need to copy over all the hdf5 files (files with extension .h5).  These are large files stored in Git Large File Storage, and they are usually holograms.  Are they ever used in the tests?

**Comment by victoriahwang89** [comment]
I removed the .h5 files and the tests still run correctly.

**Comment by victoriahwang89** [comment]
I removed the .h5 files and the tests still run correctly.

**Comment by vnmanoharan** [comment]
I think we might need a clean commit here, one without the hdf5 files in the history.  Here are some instructions:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

It's not that the .h5 files are sensitive data--it's that they are large and will slow down the repository (though I might not understand completely how git LFS works).

**Comment by vnmanoharan** [comment]
I think we might need a clean commit here, one without the hdf5 files in the history.  Here are some instructions:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

It's not that the .h5 files are sensitive data--it's that they are large and will slow down the repository (though I might not understand completely how git LFS works).

**Comment by victoriahwang89** [comment]
I followed the instructions and removed the hdf5 files from the history. I also committed some more changes related to calculating the complex Ricatti-Bessel functions and adding the Mie solutions for absorbing media from Fu and Sudiarta (as well as tests).

**Pull request merged**
