### PR TITLE
Fixed some small bugs and changed far field diff_scat_intensity() calculation to prevent rounding errors

### PR DESCRIPTION
**Pull request by AnnieStephenson**

### CODE REVIEW

**Comment by vnmanoharan** [comment]
Looks good to me.  @jeromefung, if you have a moment can you review these changes to the pure Python version of your Mie code?

**Comment by jeromefung** [comment]
I'm going to have to remind myself of a few things I haven't thought about
in a while, but I'd be happy to take a look -- most likely midweek.

**Comment by jeromefung** [comment]
Looks OK to me.

**Comment by vnmanoharan** [comment]
Thanks, @jeromefung.

**Pull request merged**
